spring.application.name=bakdatacodingchallenge


spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/querydb}
spring.datasource.username=${DB_USER:egeozturk}
spring.datasource.password=${DB_PASSWORD:}

app.sql.dialect=${APP_SQL_DIALECT:postgres}